QUnit.testSuites([
    { name: "simple closure core Test Suite", path: "./simple-closures-core.html" },
    { name: "simple closure events Test Suite", path: "./simple-closures-events.html" },
    { name: "simple closure visible Test Suite", path: "./simple-closures-visible.html" },
    { name: "simple closure forms Test Suite", path: "./simple-closures-forms.html" },
    { name: "simple closure center Test Suite", path: "./simple-closures-center.html" },
    { name: "simple closure Test Suite", path: "./simple-closures.html" },
    { name: "multiple closure core Test Suite", path: "./multiple-closures-core.html" },
    { name: "multiple closure events Test Suite", path: "./multiple-closures-events.html" },
    { name: "multiple closure visible Test Suite", path: "./multiple-closures-visible.html" },
    { name: "multiple closure forms Test Suite", path: "./multiple-closures-forms.html" },
    { name: "multiple closure Test Suite", path: "./multiple-closures.html" },
    { name: "zzDom.zz closure function core Test Suite", path: "./zz-closures-core.html" },
    { name: "zzDom.zz closure function utils Test Suite", path: "./zz-closures-utils.html" },
    { name: "zzDom.zz closure function Test Suite", path: "./zz-closures.html" },
    { name: "plugins closure Test Suite", path: "./plugins-closures.html" },

    { name: "simple node core Test Suite", path: "./node-core-simple.html" },
    { name: "simple node zz Test Suite", path: "./node-zz-simple.html" },
    { name: "simple node center Test Suite", path: "./node-plugin-center-simple.html" },
    { name: "simple node events Test Suite", path: "./node-plugin-events-simple.html" },
    { name: "simple node forms Test Suite", path: "./node-plugin-forms-simple.html" },
    { name: "simple node utils Test Suite", path: "./node-plugin-utils.html" },
    { name: "simple node visible Test Suite", path: "./node-plugin-visible-simple.html" },
    { name: "simple node full Test Suite", path: "./node-full-simple.html" },
    { name: "multiple node core Test Suite", path: "./node-core-multiple.html" },
    { name: "multiple node zz Test Suite", path: "./node-zz-multiple.html" },
    { name: "multiple node events Test Suite", path: "./node-plugin-events-multiple.html" },
    { name: "multiple node forms Test Suite", path: "./node-plugin-forms-multiple.html" },
    { name: "multiple node visible Test Suite", path: "./node-plugin-visible-multiple.html" },
    { name: "multiple node full Test Suite", path: "./node-full-multiple.html" },

    { name: "simple gcc Test Suite", path: "./simple-gcc.html" },
    { name: "multiple gcc Test Suite", path: "./multiple-gcc.html" },
    { name: "zzDom.zz gcc compiler Test Suite", path: "./zz-gcc.html" },
    { name: "plugins gcc Test Suite", path: "./plugins-gcc.html" },
    { name: "simple gcc concat Test Suite", path: "./simple-gcc-concat.html" },
    { name: "multiple gcc concat Test Suite", path: "./multiple-gcc-concat.html" },
    { name: "zzDom.zz gcc concat Test Suite", path: "./zz-gcc-concat.html" },
    { name: "plugins gcc concat Test Suite", path: "./plugins-gcc-concat.html" },
    { name: "simple gcc debug Test Suite", path: "./simple-gcc-debug.html" },
    { name: "multiple gcc debug Test Suite", path: "./multiple-gcc-debug.html" },
    { name: "zzDom.zz gcc debug Test Suite", path: "./zz-gcc-debug.html" },
    { name: "plugins gcc debug Test Suite", path: "./plugins-gcc-debug.html" },
]);
