QUnit.testSuites([
    { name: "simple closure Test Suite", path: "./simple-closures.html" },
    { name: "multiple closure Test Suite", path: "./multiple-closures.html" },
    { name: "zzDom.zz closure function Test Suite", path: "./zz-closures.html" },
    { name: "plugins closure Test Suite", path: "./plugins-closures.html" },
    { name: "simple gcc Test Suite", path: "./simple-gcc.html" },
    { name: "multiple gcc Test Suite", path: "./multiple-gcc.html" },
    { name: "zzDom.zz gcc compiler Test Suite", path: "./zz-gcc.html" },
    { name: "plugins gcc Test Suite", path: "./plugins-gcc.html" },
    { name: "simple closure concat Test Suite", path: "./simple-closures-concat.html" },
    { name: "multiple closure concat Test Suite", path: "./multiple-closures-concat.html" },
    { name: "zzDom.zz closure concat function Test Suite", path: "./zz-closures-concat.html" },
    { name: "plugins closure concat Test Suite", path: "./plugins-closures-concat.html" },
    { name: "simple gcc concat Test Suite", path: "./simple-gcc-concat.html" },
    { name: "multiple gcc concat Test Suite", path: "./multiple-gcc-concat.html" },
    { name: "zzDom.zz gcc concat Test Suite", path: "./zz-gcc-concat.html" },
    { name: "plugins gcc concat Test Suite", path: "./plugins-gcc-concat.html" },
    { name: "simple gcc debug Test Suite", path: "./simple-gcc-debug.html" },
    { name: "multiple gcc debug Test Suite", path: "./multiple-gcc-debug.html" },
    { name: "zzDom.zz gcc debug Test Suite", path: "./zz-gcc-debug.html" },
    { name: "plugins gcc debug Test Suite", path: "./plugins-gcc-debug.html" }
]);
